apiVersion: apps/v1
kind: Deployment
metadata:
  name: workernode
  labels:
    app: workernode
spec:
  selector:
    matchLabels:
      app: workernode
  template:
    metadata:
      labels:
        app: workernode
    spec:
      containers:
      - name: workernode
        image: gcr.io/halfr-cloud-stechec/sadm
        imagePullPolicy: Always
        command: ["python", "-m", "prologin.workernode"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        securityContext:
          privileged: true
